<?php


class AppointmentsTableSeeder extends Seeder {

	public function run()
	{
		$appointments = [
			[
				'date'      => '2015-01-12',
			    'price'     => '278.59',
			    'workshop'  => 4,
			    'car_id'    => Car::findCarByLicense('SP-HB-76')->id,
			    'dealer_id' => Dealer::findDealerByName('Schaap')->id,
			    'user_id'   => Sentry::findUserByLogin('r.krol@rocit.nl')->id,
			    
			],
			[
				'date'      => '2015-06-18',
				'price'     => '312.99',
				'workshop'  => 4,
				'car_id'    => Car::findCarByLicense('SP-HB-76')->id,
				'dealer_id' => Dealer::findDealerByName('Schaap')->id,
				'user_id'   => Sentry::findUserByLogin('r.krol@rocit.nl')->id,
			],
			[
				'date'      => '2015-01-10',
				'price'     => '195.67',
				'workshop'  => 3,
				'car_id'    => Car::findCarByLicense('ZR-VG-26')->id,
				'dealer_id' => Dealer::findDealerByName('Brederode')->id,
				'user_id'   => Sentry::findUserByLogin('w.buuren@rocit.nl')->id,
			],
			[
				'date'      => '2015-07-17',
				'price'     => '688.12',
				'workshop'  => 3,
				'car_id'    => Car::findCarByLicense('ZR-VG-26')->id,
				'dealer_id' => Dealer::findDealerByName('Brederode')->id,
				'user_id'   => Sentry::findUserByLogin('w.buuren@rocit.nl')->id,
			],
			[
				'date'      => '2015-11-13',
				'price'     => '421.99',
				'workshop'  => 3,
				'car_id'    => Car::findCarByLicense('ZR-VG-26')->id,
				'dealer_id' => Dealer::findDealerByName('Brederode')->id,
				'user_id'   => Sentry::findUserByLogin('w.buuren@rocit.nl')->id,
			],
			[
				'date'      => '2015-03-04',
				'price'     => '988.32',
				'workshop'  => 1,
				'car_id'    => Car::findCarByLicense('6-KBP-9')->id,
				'dealer_id' => Dealer::findDealerByName('Orsouw')->id,
				'user_id'   => Sentry::findUserByLogin('k.horst@rocit.nl')->id,
			],
			[
				'date'      => '2015-10-18',
				'price'     => '827.14',
				'workshop'  => 1,
				'car_id'    => Car::findCarByLicense('6-KBP-9')->id,
				'dealer_id' => Dealer::findDealerByName('Orsouw')->id,
				'user_id'   => Sentry::findUserByLogin('k.horst@rocit.nl')->id,
			],
			[
				'date'      => '2015-01-12',
				'price'     => '402.30',
				'workshop'  => 1,
				'car_id'    => Car::findCarByLicense('NX-XR-22')->id,
				'dealer_id' => Dealer::findDealerByName('Mudde')->id,
				'user_id'   => Sentry::findUserByLogin('h.klaver@rocit.nl')->id,
			],
			[
				'date'      => '2015-07-17',
				'price'     => '188.00',
				'workshop'  => 1,
				'car_id'    => Car::findCarByLicense('NX-XR-22')->id,
				'dealer_id' => Dealer::findDealerByName('Mudde')->id,
				'user_id'   => Sentry::findUserByLogin('h.klaver@rocit.nl')->id,
			],
			[
				'date'      => '2015-11-01',
				'price'     => '578.65',
				'workshop'  => 1,
				'car_id'    => Car::findCarByLicense('NX-XR-22')->id,
				'dealer_id' => Dealer::findDealerByName('Mudde')->id,
				'user_id'   => Sentry::findUserByLogin('h.klaver@rocit.nl')->id,
			],
			[
				'date'      => '2015-12-12',
				'price'     => '712.87',
				'workshop'  => 1,
				'car_id'    => Car::findCarByLicense('NX-XR-22')->id,
				'dealer_id' => Dealer::findDealerByName('Mudde')->id,
				'user_id'   => Sentry::findUserByLogin('h.klaver@rocit.nl')->id,
			],
			[
				'date'      => '2015-06-17',
				'price'     => '148.99',
				'workshop'  => 6,
				'car_id'    => Car::findCarByLicense('12-XND-2')->id,
				'dealer_id' => Dealer::findDealerByName('Schaap')->id,
				'user_id'   => Sentry::findUserByLogin('k.ernst@rocit.nl')->id,
			],
			[
				'date'      => '2015-09-18',
				'price'     => '223.86',
				'workshop'  => 6,
				'car_id'    => Car::findCarByLicense('12-XND-2')->id,
				'dealer_id' => Dealer::findDealerByName('Schaap')->id,
				'user_id'   => Sentry::findUserByLogin('k.ernst@rocit.nl')->id,
			],
			[
				'date'      => '2015-12-30',
				'price'     => '195.77',
				'workshop'  => 6,
				'car_id'    => Car::findCarByLicense('12-XND-2')->id,
				'dealer_id' => Dealer::findDealerByName('Schaap')->id,
				'user_id'   => Sentry::findUserByLogin('k.ernst@rocit.nl')->id,
			],
			[
				'date'      => '2015-02-21',
				'price'     => '997.10',
				'workshop'  => 9,
				'car_id'    => Car::findCarByLicense('5-GHB-1')->id,
				'dealer_id' => Dealer::findDealerByName('Jacobsen')->id,
				'user_id'   => Sentry::findUserByLogin('r.ruiter@rocit.nl')->id,
			],
			[
				'date'      => '2015-03-01',
				'price'     => '248.87',
				'workshop'  => 2,
				'car_id'    => Car::findCarByLicense('9-KVP-24')->id,
				'dealer_id' => Dealer::findDealerByName('Wensink')->id,
				'user_id'   => Sentry::findUserByLogin('f.okma@rocit.nl')->id,
			],
			[
				'date'      => '2015-06-11',
				'price'     => '745.89',
				'workshop'  => 3,
				'car_id'    => Car::findCarByLicense('9-KVP-24')->id,
				'dealer_id' => Dealer::findDealerByName('Wensink')->id,
				'user_id'   => Sentry::findUserByLogin('f.okma@rocit.nl')->id,
			],
			[
				'date'      => '2015-08-23',
				'price'     => '699.52',
				'workshop'  => 3,
				'car_id'    => Car::findCarByLicense('9-KVP-24')->id,
				'dealer_id' => Dealer::findDealerByName('Wensink')->id,
				'user_id'   => Sentry::findUserByLogin('f.okma@rocit.nl')->id,
			],
			[
				'date'      => '2015-01-04',
				'price'     => '478.96',
				'workshop'  => 3,
				'car_id'    => Car::findCarByLicense('LN-ND-98')->id,
				'dealer_id' => Dealer::findDealerByName('Jansen')->id,
				'user_id'   => Sentry::findUserByLogin('j.bakker@rocit.nl')->id,
			],
			[
				'date'      => '2015-04-11',
				'price'     => '199.12',
				'workshop'  => 3,
				'car_id'    => Car::findCarByLicense('LN-ND-98')->id,
				'dealer_id' => Dealer::findDealerByName('Jansen')->id,
				'user_id'   => Sentry::findUserByLogin('j.bakker@rocit.nl')->id,
			],
			[
				'date'      => '2015-04-18',
				'price'     => '356.57',
				'workshop'  => 3,
				'car_id'    => Car::findCarByLicense('LN-ND-98')->id,
				'dealer_id' => Dealer::findDealerByName('Jansen')->id,
				'user_id'   => Sentry::findUserByLogin('j.bakker@rocit.nl')->id,
			],
			[
				'date'      => '2015-08-01',
				'price'     => '657.85',
				'workshop'  => 3,
				'car_id'    => Car::findCarByLicense('LN-ND-98')->id,
				'dealer_id' => Dealer::findDealerByName('Jansen')->id,
				'user_id'   => Sentry::findUserByLogin('j.bakker@rocit.nl')->id,
			],
			[
				'date'      => '2015-10-18',
				'price'     => '112.01',
				'workshop'  => 3,
				'car_id'    => Car::findCarByLicense('LN-ND-98')->id,
				'dealer_id' => Dealer::findDealerByName('Jansen')->id,
				'user_id'   => Sentry::findUserByLogin('j.bakker@rocit.nl')->id,
			],
			[
				'date'      => '2015-11-22',
				'price'     => '475.88',
				'workshop'  => 2,
				'car_id'    => Car::findCarByLicense('LN-ND-98')->id,
				'dealer_id' => Dealer::findDealerByName('Jansen')->id,
				'user_id'   => Sentry::findUserByLogin('j.bakker@rocit.nl')->id,
			],
			[
				'date'      => '2015-08-21',
				'price'     => '226.24',
				'workshop'  => 2,
				'car_id'    => Car::findCarByLicense('1-EDF-2')->id,
				'dealer_id' => Dealer::findDealerByName('Brederode')->id,
				'user_id'   => Sentry::findUserByLogin('a.smit@rocit.nl')->id,
			],
			[
				'date'      => '2015-10-25',
				'price'     => '444.36',
				'workshop'  => 2,
				'car_id'    => Car::findCarByLicense('1-EDF-2')->id,
				'dealer_id' => Dealer::findDealerByName('Brederode')->id,
				'user_id'   => Sentry::findUserByLogin('a.smit@rocit.nl')->id,
			],
			[
				'date'      => '2015-12-19',
				'price'     => '685.32',
				'workshop'  => 2,
				'car_id'    => Car::findCarByLicense('1-EDF-2')->id,
				'dealer_id' => Dealer::findDealerByName('Brederode')->id,
				'user_id'   => Sentry::findUserByLogin('a.smit@rocit.nl')->id,
			],
			[
				'date'      => '2015-01-05',
				'price'     => '800.55',
				'workshop'  => 2,
				'car_id'    => Car::findCarByLicense('99-ND-NN')->id,
				'dealer_id' => Dealer::findDealerByName('Jacobsen')->id,
				'user_id'   => Sentry::findUserByLogin('b.oosterhuis@rocit.nl')->id,
			],
			[
				'date'      => '2015-01-17',
				'price'     => '325.74',
				'workshop'  => 2,
				'car_id'    => Car::findCarByLicense('99-ND-NN')->id,
				'dealer_id' => Dealer::findDealerByName('Jacobsen')->id,
				'user_id'   => Sentry::findUserByLogin('b.oosterhuis@rocit.nl')->id,
			],
			[
				'date'      => '2015-03-11',
				'price'     => '199.02',
				'workshop'  => 2,
				'car_id'    => Car::findCarByLicense('99-ND-NN')->id,
				'dealer_id' => Dealer::findDealerByName('Jacobsen')->id,
				'user_id'   => Sentry::findUserByLogin('b.oosterhuis@rocit.nl')->id,
			],
			[
				'date'      => '2015-11-29',
				'price'     => '658.09',
				'workshop'  => 2,
				'car_id'    => Car::findCarByLicense('99-ND-NN')->id,
				'dealer_id' => Dealer::findDealerByName('Jacobsen')->id,
				'user_id'   => Sentry::findUserByLogin('b.oosterhuis@rocit.nl')->id,
			],
			[
				'date'      => '2015-01-10',
				'price'     => '984.56',
				'workshop'  => 2,
				'car_id'    => Car::findCarByLicense('2-ABC-3')->id,
				'dealer_id' => Dealer::findDealerByName('Duursma')->id,
				'user_id'   => Sentry::findUserByLogin('p.klaassen@rocit.nl')->id,
			],
			[
				'date'      => '2015-01-24',
				'price'     => '879.32',
				'workshop'  => 2,
				'car_id'    => Car::findCarByLicense('2-ABC-3')->id,
				'dealer_id' => Dealer::findDealerByName('Duursma')->id,
				'user_id'   => Sentry::findUserByLogin('p.klaassen@rocit.nl')->id,
			],
			[
				'date'      => '2015-04-25',
				'price'     => '803.98',
				'workshop'  => 2,
				'car_id'    => Car::findCarByLicense('2-ABC-3')->id,
				'dealer_id' => Dealer::findDealerByName('Duursma')->id,
				'user_id'   => Sentry::findUserByLogin('p.klaassen@rocit.nl')->id,
			],
			[
				'date'      => '2015-08-28',
				'price'     => '947.23',
				'workshop'  => 2,
				'car_id'    => Car::findCarByLicense('2-ABC-3')->id,
				'dealer_id' => Dealer::findDealerByName('Duursma')->id,
				'user_id'   => Sentry::findUserByLogin('p.klaassen@rocit.nl')->id,
			],
			[
				'date'      => '2015-01-24',
				'price'     => '101.33',
				'workshop'  => 2,
				'car_id'    => Car::findCarByLicense('SX-XR-57')->id,
				'dealer_id' => Dealer::findDealerByName('Schaap')->id,
				'user_id'   => Sentry::findUserByLogin('j.jansma@rocit.nl')->id,
			],
			[
				'date'      => '2015-08-28',
				'price'     => '599.84',
				'workshop'  => 2,
				'car_id'    => Car::findCarByLicense('SX-XR-57')->id,
				'dealer_id' => Dealer::findDealerByName('Schaap')->id,
				'user_id'   => Sentry::findUserByLogin('j.jansma@rocit.nl')->id,
			],
		];

		foreach($appointments as $appointment)
		{
			Appointment::create($appointment);
		}
	}

}